name: CI
on:
  push:
    paths:
      - "**/*.json"
      - "**/*.ts"
      - .github/workflows/*.yml
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Print version
        run: deno --version

      - name: Check hashes
        run: |
          d='[0-9]'
          sub="s/$d$d$d$d-$d$d-$d$d/YYYY-MM-DD/g"

          sed -i -e $sub mod.ts
          md5sum devices.json mod.ts > hash.md5

          deno run --no-check --quiet --allow-read=devices --allow-write=devices.json,mod.ts --allow-run=deno generate.ts

          sed -i -e $sub mod.ts
          md5sum --check hash.md5
